# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the twrp-6.0 branch
  - push
  - pull_request

  # Allows you to run this workflow manually from the Actions tab
  - workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Download GCC
        run: git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.8 ~/gcc -b lollipop-release

      - name: Do it
        run: |
              export ARCH=arm CROSS_COMPILE=~/gcc/bin/arm-linux-androideabi-
              cd $GITHUB_WORKSPACE
              mkdir out
              make O=out clean mrproper
              make O=out v2800_defconfig
              make O=out -j$(nproc --all)
              
      - uses: actions/upload-artifact@v2
        with:
             name: zImage-dtb
             path: out/arch/arm/boot/zImage-dtb

